app_shopware_api_get:
  path: shopware/api/get/{action}
  controller: App\LmaDev\ShopwareApiBundle\Controller\ShopwareApiController:get
app_shopware_api_post:
  path: shopware/api/post/{action}
  controller: App\LmaDev\ShopwareApiBundle\Controller\ShopwareApiController:post
app_shopware_api_put:
  path: shopware/api/put/{action}/{productID}
  controller: App\LmaDev\ShopwareApiBundle\Controller\ShopwareApiController::put